# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_hsg0dou1U1gJo8Na7HxEEPKenVFZ1Tp
"""

import pandas as pd
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import joblib

nltk.download('stopwords')
nltk.download('wordnet')

df = pd.read_csv("dataset.csv")

df.head()

df.info()

df.isnull().sum()

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
  text = text.lower()
  text = text.translate(str.maketrans('','',string.punctuation))

  words = text.split()
  words = [word for word in words if word not in stop_words]
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

df['Clean_text'] = df['text'].apply(preprocess)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['Clean_text'])
y = df['sentiment']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy : ", accuracy_score(y_test, y_pred))

print("Classifcation Report : ", classification_report(y_test, y_pred))

print("Confusion Matrix : ", confusion_matrix(y_test, y_pred))

joblib.dump(model, 'model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')

def Predict_sentiment(text):
  text = preprocess(text)
  vec = vectorizer.transform([text])
  prediction = model.predict(vec)[0]
  probs = model.predict_proba(vec)

  print("Predicted Sentiment : ", prediction)
  print("Probabilities : ", probs)

while True:
    user_input = input("\nEnter your sentence or type exit: ")

    if user_input.lower() == "exit":
        break

    Predict_sentiment(user_input)